### ISSUE TITLE
clean output of matplitlib svg file before saving

### ISSUE THREAD

**Issue by psilentp** [FlyRanch/figurefirst#14]
deal with this known bug:

https://bugs.launchpad.net/inkscape/+bug/1533058

http://stackoverflow.com/questions/39380761/how-to-set-miterlimit-when-saving-as-svg-with-matplotlib

**Comment by ptweir** [comment]
added fix_mpl_svg to mpl_functions.py and it seems to work. You guys should feel free to move it or change it if you want!
