### ISSUE TITLE
svgitem with same name as figure object causes a silent error

### ISSUE THREAD

**Issue by florisvb** [FlyRanch/figurefirst#16]
If you have svgitems (like a text box) with the same name as a figurefirst:figure, the figures do not get generated (the svgitems do).

See attached file (rename to .svg instead of .txt - github does not allow uploading svgs)

[svgitem_figure_clash.txt](https://github.com/FlyRanch/figurefirst/files/503806/svgitem_figure_clash.txt)

**Comment by psilentp** [comment]
svgitems are created in their own tree. To use them in a hierarchy they need to be grouped using the figurefirst:svggroup tag.
