### ISSUE TITLE
Remove *.swp files

### ISSUE THREAD

**Issue by scollis** [FlyRanch/figurefirst#21]
Causes Vim to complain.. not needed.

**Comment by clbarnes** [comment]
I think this is resolved.

**Comment by psilentp** [comment]
Thanks - I never did see any .swp files. Were you able to find them? Closing the issue.

**Comment by clbarnes** [comment]
Yes, I deleted one in https://github.com/FlyRanch/figurefirst/commit/41c83ec81bf32ea9fa161ff7592337bd761c69a0 and added them to the gitignore in https://github.com/FlyRanch/figurefirst/commit/136850f567e9e51750a1bf995e7652a8cd614b5b
