### ISSUE TITLE
Feature idea: add a save_to_fifi_layout method

### ISSUE THREAD

**Issue by ptweir** [FlyRanch/figurefirst#24]
I don't think we have this already. The idea is that if someone has already made a figure using mpl, it would be cool to let them save it to a figurefirst svg layout file, then enter the iterative workflow from there.

**Comment by florisvb** [comment]
I'll play around with getting something like this working.

**Comment by florisvb** [comment]
I just pushed this functionality, you can see it in operation here:

https://github.com/FlyRanch/figurefirst/blob/master/examples/mpl_to_svg_layout/mpl_fig_to_figurefirst_svg.ipynb

Let me know if you think it can be improved, but closing this issue for now!
