### ISSUE TITLE
'imp' module not available in Python 3.12

### ISSUE THREAD

**Issue by CharlesXu-Jingyue** [FlyRanch/figurefirst#66]
Starting from Python 3.12, 'imp' is removed in favor of 'importlib'.

A quick fix is to replace
```
import imp
```
with
``` 
import importlib as imp
```

https://docs.python.org/3.10/library/imp.html
https://docs.python.org/3.10/library/importlib.html

**Comment by florisvb** [comment]
Thanks, I updated all the import calls to importlib.
